server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: streamGroup

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka
  instance:
    #在eureka的Status中显示的名称
    instance-id: receive-8802.com
    #访问路径显示ip
    prefer-ip-address: true
    #eureka客户端向服务端发送心跳的时间间隔，默认是30秒
    lease-renewal-interval-in-seconds: 2
    #eureka服务端在收到最后一次心跳后等待时间上限，默认90秒，超时踢出服务
    lease-expiration-duration-in-seconds: 5